"""initial schema + append-only audit trigger

Revision ID: d8847faf5e20
Revises: 
Create Date: 2026-07-27 19:02:47.012917
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd8847faf5e20'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_correlation', 'audit_log', ['correlation_id'], unique=False)
    op.create_index('ix_audit_event_type', 'audit_log', ['event_type'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metrics_strategy_name', 'metrics', ['strategy_id', 'name'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('asset_class', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_positions_symbol', 'positions', ['symbol'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_strategies_id_version', 'strategies', ['strategy_id', 'version'], unique=True)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('strategy_id', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('asset_class', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id')
    )
    op.create_index('ix_trades_strategy', 'trades', ['strategy_id'], unique=False)
    op.create_table('hypotheses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_pk', sa.Integer(), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('predicted_delta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verdict', sa.String(length=24), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_pk'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Append-only enforcement for audit_log (invariant: audit trail is immutable, PRD §19).
    # A DB-level trigger blocks UPDATE and DELETE so no code path — not even a bug or a
    # compromised app account — can rewrite history. INSERT is allowed.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION icarus_block_audit_mutation()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_log is append-only (PRD §19): % blocked', TG_OP;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_log_append_only
        BEFORE UPDATE OR DELETE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION icarus_block_audit_mutation();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_log_append_only ON audit_log;")
    op.execute("DROP FUNCTION IF EXISTS icarus_block_audit_mutation();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hypotheses')
    op.drop_index('ix_trades_strategy', table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_strategies_id_version', table_name='strategies')
    op.drop_table('strategies')
    op.drop_index('ix_positions_symbol', table_name='positions')
    op.drop_table('positions')
    op.drop_index('ix_metrics_strategy_name', table_name='metrics')
    op.drop_table('metrics')
    op.drop_index('ix_audit_event_type', table_name='audit_log')
    op.drop_index('ix_audit_correlation', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
